### ISSUE TITLE
Option to always open on a specific monitor

### ISSUE THREAD

**Issue by CWSpear** [CWSpear/hyperterm-visor#6]
I personally like that it opens on the monitor where my mouse is, but I'd like to add support for always opening on a specific monitor.

I'd also like to look into opening on the active monitor on macOS (which is not always where the mouse is), and adding an option for that if it's possible.

**Comment by ghost** [comment]
Related: Once opened in a desktop, hypervisor "drags" the desktop back to primary (sets that desktop to primary) when hypervisor is reopened.

**Comment by CWSpear** [comment]
I don't follow...

**Comment by ghost** [comment]
To reproduce:
1. Install hypervisor and hyperterm as in docs.
2. Open multiple virtual desktops in OSX.
3. Open a hyperterm window (shortcut or otherwise).
4. Toggle it closed with visor shortcut (or not).
5. Switch desktops.
6. Hit visor shortcut.
7. Original virtual desktop will be set as primary and visor will open.

**Comment by CWSpear** [comment]
This repository is no longer maintained. Feel free to fork. Probably doesn't work with the latest version of Hyper 1, and certainly unlikely to work with Hyper 2.
